path: dataset
train: train_equal/images
val: val/images
test: test/images

# Classes
names:
  0: Banana
  1: Peeled Orange
  2: Pomegranate
  3: Grapes
  4: Raspberries
  5: Apple
  6: Orange

augmentations:
  hsv_h: 0.015 # (float) image HSV-Hue augmentation (fraction)
  hsv_s: 0.7 # (float) image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4 # (float) image HSV-Value augmentation (fraction)
  degrees: 0.0 # (float) image rotation (+/- deg)
  translate: 0.1 # (float) image translation (+/- fraction)
  scale: 0.5 # (float) image scale (+/- gain)
  shear: 0.0 # (float) image shear (+/- deg)
  perspective: 0.0 # (float) image perspective (+/- fraction), range 0-0.001
  flipud: 0.3 # (float) image flip up-down (probability)
  fliplr: 0.5 # (float) image flip left-right (probability)
  # bgr: 0.0 # (float) image channel BGR (probability)
  mosaic: 0.0 # (float) image mosaic (probability)
  mixup: 0.1 # (float) image mixup (probability)
  copy_paste: 0.3 # (float) segment copy-paste (probability)
  auto_augment: randaugment # (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
  erasing: 0.4 # (float) probability of random erasing during classification training (0-0.9), 0 means no erasing, must be less than 1.0.
  crop_fraction: 1.0 # (float) image crop fraction for classification (0.1-1), 1.0 means no crop, must be greater than 0.
  advanced_blur: 0.3
  color_jitter: 0.5
  downscale: 0.3
  downscale_min: 256
  downscale_max: 480
  gaussian_blur: 0.5
  motion_blur: 0.2
  image_compression: 0.1
  ios_noise: 0.4
  random_brightness_contrast: 0.5
  random_gamma: 0.3
  random_shadow: 0.5
  sharpen: 0.3
  regional_blur: 0.4
  max_number_of_dots: 15
  min_radius: 0.01
  max_radius: 0.1
  blur_value: [151, 211]